name: Node.js

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Nodejs Build
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFARE_API_TOKEN }}
          accountId: 1022cfdc0fee29412980cc9f5d9b326c
          projectName: test-devops
          directory: dist
          wranglerVersion: '3'